name: Upload updater form
description: Upload a multipart form data to the setted ip
inputs:
  urls: # id of input
    description: url to send the request
    required: true
  fields:
    description: 'fields of the form ej: field1=value field2=@path/to/file field3="@path/to/file with space"'
    required: true
  insecure:
    description: allow insecure call with https
  dry-run:
    description: dry run update. only valid value is true, otherwise will not run dry run
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node20"
  main: "dist/index.js"
